name: Test Workflow

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: oryd/ory:v1.1.0
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Say hello
        run: |
          directory=${1:-./scripts}
          echo "The files in $directory are:"
          ls -1 "$directory"
          ./scripts/say_hello.sh
